### ISSUE TITLE
JavaNullPointerException

### ISSUE THREAD

**Issue by SongRb** [Angel-ML/sona#47]
java.lang.NullPointerException
        at sun.net.util.URLUtil.urlNoFragString(URLUtil.java:50)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:512)
        at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:484)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:238)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at net.qihoo.spinner.HdfsClassLoader.loadClass(HdfsClassLoader.java:35)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.qihoo.spinner.HYReflection.newInstance(HYReflection.java:70)
        at net.qihoo.spinner.SpinnerViewFs.initializeProperties(SpinnerViewFs.java:18)
        at net.qihoo.spinner.SpinnerDistributedFileSystem.initialize(SpinnerDistributedFileSystem.java:47)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2689)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:386)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$cleanupStagingDirInternal$1(Client.scala:199)
        at org.apache.spark.deploy.yarn.Client.cleanupStagingDir(Client.scala:217)
        at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:182)
        at org.apache.spark.deploy.yarn.Client.run(Client.scala:1155)
        at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1523)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:880)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at net.qihoo.spinner.HYReflection.newInstance(HYReflection.java:93)
        at net.qihoo.spinner.SpinnerViewFs.initializeProperties(SpinnerViewFs.java:18)
        at net.qihoo.spinner.SpinnerDistributedFileSystem.initialize(SpinnerDistributedFileSystem.java:47)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2689)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:386)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$cleanupStagingDirInternal$1(Client.scala:199)
        at org.apache.spark.deploy.yarn.Client.cleanupStagingDir(Client.scala:217)
        at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:182)
        at org.apache.spark.deploy.yarn.Client.run(Client.scala:1155)
        at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1523)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:880)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NullPointerException
        at sun.net.util.URLUtil.urlNoFragString(URLUtil.java:50)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:512)
        at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:484)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:238)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at net.qihoo.spinner.HdfsClassLoader.loadClass(HdfsClassLoader.java:35)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.qihoo.spinner.HYReflection.newInstance(HYReflection.java:70)
        ... 15 more

**Comment by ZengDongDon** [comment]
you can see the existing issues of "gbdt training error"，it solve the problem
