### ISSUE TITLE
java.lang.NoSuchMethodError in JsonUtils

### ISSUE THREAD

**Issue by zxsimple** [Angel-ML/sona#5]
Need I update the `angel-mlcore` library or `json4s` library?

```
An exception or error caused a run to abort: org.json4s.native.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue; 
java.lang.NoSuchMethodError: org.json4s.native.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
	at com.tencent.angel.ml.core.utils.JsonUtils$.parseAndUpdateJson(JsonUtils.scala:400)
	at org.apache.spark.angelml.param.AngelGraphParams$class.updateFromJson(AngelGraphParams.scala:31)
	at org.apache.spark.angelml.classification.AngelClassifier.updateFromJson(AngelClassifier.scala:31)
	at org.apache.spark.angelml.classification.AngelClassifier.updateFromJson(AngelClassifier.scala:31)
	at org.apache.spark.angelml.param.ParamsHelper$class.finalizeConf(ParamsHelper.scala:43)
	at org.apache.spark.angelml.classification.AngelClassifier.finalizeConf(AngelClassifier.scala:31)
	at org.apache.spark.angelml.classification.AngelClassifier.train(AngelClassifier.scala:177)
	at org.apache.spark.angelml.classification.AngelClassifier.train(AngelClassifier.scala:31)
	at org.apache.spark.angelml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.angelml.classification.AngelClassificationSuite$$anonfun$1.apply$mcV$sp(AngelClassificationSuite.scala:31)
	at org.apache.spark.angelml.classification.AngelClassificationSuite$$anonfun$1.apply(AngelClassificationSuite.scala:18)
	at org.apache.spark.angelml.classification.AngelClassificationSuite$$anonfun$1.apply(AngelClassificationSuite.scala:18)
```

**Comment by zxsimple** [comment]
I'm compiling and running SONA with Spark 2.1, the required `json4s` should be 3.2.11 and `json4s-scalp` version should be 3.3.0
